### ISSUE TITLE
when i proxy conda repositories,  i got error

### ISSUE THREAD

**Issue by george-wang2016** [sonatype-nexus-community/nexus-repository-conda#11]
i deployed nexus3 of version 3.16.1-02 on linux , after installed the conda proxy plugin v 0.3, i created a proxy.
so i try to install package from my client, anaconda2 with conda 4.5.12, using -c option, i got error below 

Solving environment: failed

CondaHTTPError: HTTP 404 NOT FOUND for url <http://10.1.1.3:8088/nexus3/repository/conda-proxy-official/noarch/repodata.json>
Elapsed: 00:00.005304

The remote server could not find the noarch directory for the
requested channel with url: http://10.1.1.3:8088/nexus3/repository/conda-proxy-official

As of conda 4.3, a valid channel must contain a `noarch/repodata.json` and
associated `noarch/repodata.json.bz2` file, even if `noarch/repodata.json` is
empty. please request that the channel administrator create
`noarch/repodata.json` and associated `noarch/repodata.json.bz2` files.
$ mkdir noarch
$ echo '{}' > noarch/repodata.json
$ bzip2 -k noarch/repodata.json

You will need to adjust your conda configuration to proceed.
Use `conda config --show channels` to view your configuration's current state.
Further configuration help can be found at <https://conda.io/docs/config.html>.

**Comment by bhamail** [comment]
@george-wang2016 Could you provide the full command line you used? I'm trying to reproduce the issue.

Also, what is the `Remote Storage:` setting for this proxy repository in Nexus?

I may be missing the point, but if you are reporting a problem with the remote conda repository (namely that the remote repository is missing the `noarch` files), then you should probably instead report this to the upstream channel administrator. We don't have any control over the content of the remote repository.

**Comment by george-wang2016** [comment]
my command:     conda install -c http://10.1.1.3:8088/nexus3/repository/conda-proxy-official/ --override-channels numpy

the remote storage address of conda-proxy-official is : https://repo.anaconda.com/pkgs/main/

i have checked the site,which includes  noarch dir  and  repodata.json  and repodata.json.bz2

**Comment by bhamail** [comment]
I think you may have be caught between some changes made to the implementation, and a delay we had in updating the docs to match that change. The current implementation uses a "higher level" URL to access the conda remote repo, and moves the "channel" into the client command. This allows you to access all the channels with just one Proxy Repo configured in Nexus.

To verify this, could you do the following:

1. Delete your existing conda proxy repo from Nexus. Stop Nexus.
2. Delete the conda format .kar (or jar if you've installed using the older method).
3. Pull the latest conda format code and rebuild the conda format plugin with the .kar bundle command.
4. Install the new .kar (see: [Easiest Install](https://github.com/sonatype-nexus-community/nexus-repository-conda#easiest-install)), start Nexus, and create a new conda-proxy repo. See these updated docs: [Proxying Conda...](https://github.com/sonatype-nexus-community/nexus-repository-conda/blob/master/docs/CONDA_USER_DOCUMENTATION.md#proxying-the-conda-continuum-repository)

Notice the remote storage URL no longer includes the channel ("main"), 
```
https://repo.continuum.io/pkgs/
```
and the client command now appends the channel ("main") to the -c parameter url.
```
conda install -c http://localhost:8081/repository/conda-proxy/main numpy
```

Please let me know if that solves the problem for you.

**Comment by george-wang2016** [comment]
thank you very much,  resolved!
