### ISSUE TITLE
Missing Releases for Jar files

### ISSUE THREAD

**Issue by dmpe** [sonatype-nexus-community/nexus-repository-conda#14]
* **What are you trying to do?**
Install this package

* **Anything else?**

There are no releases in this repository.....Even if it is just 0.0.3, it would be valuable to have them

 cc @DarthHater @bhamail

**Comment by bhamail** [comment]
@dmpe Good point. We're looking into a way to publish a prebuilt bundle via CI.

**Comment by DarthHater** [comment]
We've started publishing the kar for this to Maven Central:

https://search.maven.org/search?q=a:nexus-repository-conda

Is this sufficient?

**Comment by dmpe** [comment]
Yes, this is great news, thank you!
