### ISSUE TITLE
Change CondaRecipeSupport to reference the constants in CondaPathUtils

### ISSUE THREAD

**Issue by bhamail** [sonatype-nexus-community/nexus-repository-conda#8]
Thanks for creating an issue! Please fill out this form so we can be
sure to have all the information we need, and to minimize back and forth.

* **What are you trying to do?**
Refactor hard coded strings to use constants

cc @DarthHater @bhamail

**Comment by DarthHater** [comment]
Fixed in #10 , feel free to open if you feel otherwise!
